### ISSUE TITLE
Schema inference doesn't support pandas-native types

### ISSUE THREAD

**Issue by FirefoxMetzger** [logicalclocks/hopsworks#1290]
I am trying out Hopsworks on a toy problem, and I noticed that the type inference/conversion breaks down when I use pandas-native types. Instead, I have to use numpy types. For example:

```python
import pandas as pd
import numpy as np
import hopsworks

ctx = hopsworks.login()
fs = ctx.get_feature_store()

feature_group = fs.get_or_create_feature_group(
    name="foo",
    version="1",
    description="an example",
    primary_key=['index'],
)

# insertion using numpy types works fine
np_data = pd.DataFrame({
    "index": np.arange(10),
    "feature": np.arange(10, 0, -1)
}).astype(np.int8)

feature_group.insert(np_data)

# fails because it can't handle pandas-native Int8
pd_data = pd.DataFrame({
    "index": np.arange(10),
    "feature": np.arange(10, 0, -1)
}).astype(pd.Int8Dtype())

feature_group.insert(pd_data)  # FeatureStoreException
```

<details>
<summary>stacktrace</summary>

```python
ValueError                                Traceback (most recent call last)
File c:\Users\Sebastian\Documents\Coding-Projects\!deploy_test\.venv\lib\site-packages\hsfs\engine\python.py:368, in Engine.parse_schema_feature_group(self, dataframe, time_travel_format)
    367 try:
--> 368     converted_type = self._convert_pandas_type(
    369         feat_type, arrow_schema.field(feat_name).type
    370     )
    371 except ValueError as e:

File c:\Users\Sebastian\Documents\Coding-Projects\!deploy_test\.venv\lib\site-packages\hsfs\engine\python.py:389, in Engine._convert_pandas_type(self, dtype, arrow_type)
    387     return self._infer_type_pyarrow(arrow_type)
--> 389 return self._convert_simple_pandas_type(dtype)

File c:\Users\Sebastian\Documents\Coding-Projects\!deploy_test\.venv\lib\site-packages\hsfs\engine\python.py:419, in Engine._convert_simple_pandas_type(self, dtype)
    417     return "string"
--> 419 raise ValueError(f"dtype '{dtype}' not supported")

ValueError: dtype 'Int8' not supported

During handling of the above exception, another exception occurred:

FeatureStoreException                     Traceback (most recent call last)
Cell In[66], line 5
      1 pd_data = pd.DataFrame({
      2     "index": np.arange(10),
...
--> 372         raise FeatureStoreException(f"Feature '{name}': {str(e)}")
    373     features.append(feature.Feature(name, converted_type))
    374 return features

FeatureStoreException: Feature 'index': dtype 'Int8' not supported
```
</details>

Are there any plans on supporting this? It would make writing extractors much easier, e.g., we can start relying on automatic type inference via [`convert_dtypes`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.convert_dtypes.html) to convert `object` type data to more sensible dtypes before writing them to the feature store.

**Comment by moritzmeister** [comment]
Hi,
which version of the hopsworks python library or hsfs are you using?
Are you running this against our serverless app.hopsworks.ai instance or your own cluster?

We have extended support for these types in Hopsworks 3.1.
So if you are using app.hopsworks.ai you will be able to use them soon, when we roll out the upgrade.
If you are running your own cluster and are running Hopsworks 3.1, you can install `hsfs==3.1.0.rc0`.

**Comment by FirefoxMetzger** [comment]
> which version of the hopsworks python library or hsfs are you using?

Oh right, sorry I should have mentioned that. Here are the versions I am using

```powershell
> pip freeze | Select-String "hopsworks|hsfs|numpy|pandas"  

hopsworks==3.0.5
hsfs==3.0.5
numpy==1.24.1
pandas==1.5.3
```

> Are you running this against our serverless app.hopsworks.ai instance or your own cluster?

I am indeed running against the serverless app.

> We have extended support for these types in Hopsworks 3.1.
So if you are using app.hopsworks.ai you will be able to use them soon, when we roll out the upgrade.

Excellent! Do you have a rough estimate when the update will roll out? (days, weeks, months)

**Comment by moritzmeister** [comment]
I think it will be out in the next two weeks or so.

**Comment by moritzmeister** [comment]
Closing this issue :)
