### ISSUE TITLE
SSL Handshake Certificate Error

### ISSUE THREAD

**Issue by yassine-rd** [logicalclocks/hopsworks#1357]
Hi,

So I'm trying to insert my Feature Groupe into the Hopswokrs Feature Store and I'm recieving these message:

```
%3|1686429911.906|FAIL|Air-de-Yassine.lan#producer-1| [thrd:ssl://3.142.251.253:9092/bootstrap]: ssl://3.142.251.253:9092/bootstrap: SSL handshake failed: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed: broker certificate could not be verified, verify that ssl.ca.location is correctly configured or root CA certificates are installed (brew install openssl) (after 112ms in state SSL_HANDSHAKE, 9 identical error(s) suppressed)
```

I have already installed the OpenSLL lib using brew.
The Feature Groupe is created but the data is never ingested.

Am I missing something here?

**Comment by SirOibaf** [comment]
@yassine-rd - the issue is related to the version of librdkafka that brew installs. Have a look at this post on our community forum for instructions on how to fix it: https://community.hopsworks.ai/t/ssl-handshake-failed-on-macos-hopsworks-serverless/886/4?u=fabio
