### ISSUE TITLE
Errors in the FeatureView>Training Data documentation

### ISSUE THREAD

**Issue by SebastianoMeneghin** [logicalclocks/hopsworks#1431]
The documentation [here reported](https://docs.hopsworks.ai/3.4/user_guides/fs/feature_view/training-data/#deletion) contains some errors. 

Indeed, to delete a training data version, you need to pass during the function call a value for the variable named **"training_dataset_version"**, while in the documentation is written:
*% delete a training data version
feature_view.delete_training_dataset(**version**=1)*

Instead, when you want to delete all the possible training datasets, you need to use the function **"delete_all_training_datasets()"**, while on the documentation is written:
*% delete all training datasets
feature_view.**delete_training_dataset()***

**Comment by SirOibaf** [comment]
Hi @SebastianoMeneghin - Thanks for reporting this - We updated the documentation
