### ISSUE TITLE
Hopsworks never installs with Poetry

### ISSUE THREAD

**Issue by jshuadvd** [logicalclocks/hopsworks#1504]
I am attempting to add the hopsworks package into my project via poetry. 

I have attempted to install multiple versions. Starting with the default version poetry downloads which is `3.4.4` then `3.5.0 & 3.7.0`.

The issue is that `Resolving dependencies` loop just keeps running indefinitely and the package never installs. 

I normally use `python 3.11.8`, but have also tried each install with all versions `3.8 - 3.11.8`. 

I do not have this issue with any other package using poetry.

Any help would be greatly appreciated. Thank you!

Here is my latest `pyproject.toml` file if needed.  
```
[tool.poetry.dependencies]
python = ">=3.9,<3.9.7 || >3.9.7,<3.10"
jupyter = "^1.0.0"
pandas = "^2.1.4"
pyarrow = "^14.0.2"
tdqm = "^0.0.1"
plotly = "^5.18.0"
numpy = "^1.26.3"
requests = "^2.31.0"
scikit-learn = "^1.4.0"
xgboost = "^2.0.3"
lightgbm = "^4.3.0"
optuna = "^3.5.0"
python-dotenv = "^1.0.1"
```

**Comment by robzor92** [comment]
Hey @jshuadvd! Thank you for reporting this issue.

Can you try if this `pyproject.toml` works for you?

```
[tool.poetry.dependencies]
python = ">=3.11,<3.13"
jupyter = "^1.0.0"
pandas = "^2.1.4"
pyarrow = "^14.0.2"
tdqm = "^0.0.1"
plotly = "^5.18.0"
numpy = "^1.26.3"
requests = "^2.31.0"
scikit-learn = "^1.4.0"
xgboost = "^2.0.3"
lightgbm = "^4.3.0"
optuna = "^3.5.0"
python-dotenv = "^1.0.1"
hopsworks = "3.4.4"
```

**Comment by jshuadvd** [comment]
Hey @robzor92 You're welcome! Thank you for the quick response! 

This does work for me now! Looks like a commit was pushed to fix! 

Thank you for your help!
