### ISSUE TITLE
 Issue with date time arguments

### ISSUE THREAD

**Issue by JohnPPinto** [logicalclocks/hopsworks#1505]
Hello,

I have an issue with arguments that take datetime values.

My dataset has a feature of datetime for every hour with a datatype of period[H].

When I use the function ```FeatureView.get_batch_data``` and provide an argument to have the dataset start from 00:00 hours, it provides me the dataset from 12:00 hours. Similarly, with the end_time rather than providing the last datetime at 23:00 hours, it provides me with the last datetime of 11:00.

For eg. 
```
    # get feature store instance
    fs = ...

    # get feature view instance
    feature_view = fs.get_feature_view(...)

    # set up dates
    import datetime
    start_date = datetime.datetime(2023, 1, 1)
    end_date = datetime.datetime(2023, 1, 5)

    # get a batch of data
    df = feature_view.get_batch_data(
        start_time=start_date,
        end_time=end_date
    )

```
If I provide a datetime value of  ```datetime.datetime(2023, 1, 1)``` and ```datetime.datetime(2023, 1, 5)``` then the dataset starts from “2023-01-01 12:00:00” and ends at "2023-01-05 11:00:00".

The resulting dataframe is wrong it needs to be between “2023-01-01 00:00:00” and  "2023-01-04 23:00:00".

Installed version:
* Python 3.11.7
* hopsworks 3.4.4 
* pandas 2.1.4 

Any help will be appreciated, thanks.

**Comment by SirOibaf** [comment]
Hi @JohnPPinto ,

Thanks again for reporting this issue! As mentioned in the community thread (https://community.hopsworks.ai/t/issue-with-date-time-arguments/1068) the issue has been addressed and Hopsworks serverless should as expected.

Fixed in #1508
