### ISSUE TITLE
login user is incorrect

### ISSUE THREAD

**Issue by zhangjunqiang** [logicalclocks/hopsworks#332]
https://hopsworks.readthedocs.io/en/0.10/getting_started/setups/single_machine.html

I start with the virtualbox and  Importing an ova image.

in the process of start vm, i comes to type hopsworks0 login:

but when i type in admin@hopsworks.ai
and then password: admin.

it come out incorrect

**Comment by tkakantousis** [comment]
Are you typing these credentials in your browser or the command line terminal?
The terminal does not need credentials to ssh into. To log in into Hopsworks in your browser you should come to a page as in the first image here https://hopsworks.readthedocs.io/en/0.10/user_guide/hopsworks/firstLogin.html

**Comment by zhangjunqiang** [comment]
Thanks for yout reply, got it~
