### ISSUE TITLE
Unable to create a project

### ISSUE THREAD

**Issue by guillermo-carrasco** [logicalclocks/hopsworks#372]
Hi there,

I am trying to deploy Hopsworks with the main objective of trying the Feature Store component. To do so, I have followed [this](https://hopsworks.readthedocs.io/en/1.0/getting_started/setups/hopsworks_gcp.html) guide where it is explained how to deploy the whole stack using a GCE image. I followed all the steps and managed to get an instance up and running. 

However, when I try to create a project with the service Feature Store (or any other service), nothing happens:

![hopsworks](https://user-images.githubusercontent.com/1574147/67880427-e761c800-fb3e-11e9-8d83-87402cae4f82.png)

It stays like that and the project is never created. I have tried to create a user, thinking that maybe the problem is that I am not assigning users to the project, but the confirmation email is never sent to my email. I can see the pending request in the admin section, and can click on resend email, but nothing happens. 

The main problem is that I don't know how to debug this, could you point me in the correct direction?

Also, this is probably another issue to open, but have you considered providing a docker-based deployment? I think it would be easier to deploy than full images or native services installs. 

Thanks for your help!

**Comment by tkakantousis** [comment]
Hi @guillermo-carrasco 

For debugging, as a first step you can check if all services are up and running. You can do so from the Admin UI (accessible from your account menu on the top right) and then click on `Services`.

From cli, as root you can run the `/srv/hops/kagent/kagent/bin/status-all-local-services.sh`. Also useful are the application server logs under `/srv/hops/domains/domain1/logs/server.log`. 

You don't need to assign users to project when it is created, if no users are provided then the project's single member will be the user that created that project. For email to be sent, you need to set up your mail server config in the application server web console (default port 4848).

The GCP image is still the older version 0.10 which is also available as an virtualbox appliance if that could be more convenient for your setup https://hopsworks.readthedocs.io/en/0.10/getting_started/setups/single_machine.html#importing-an-ova-image (not available for 1.0 yet) On AWS there is a Hopsworks 1.0 AMI and you can easily install Hopsworks on a VM locally if you have a machine with at least 16GB of main memory https://hopsworks.readthedocs.io/en/1.0/getting_started/setups/single_machine.html 

We are looking into ways to make it easier to deploy Hopsworks such as Docker, but it will not be available for the next release at least (scheduled for early December)

**Comment by guillermo-carrasco** [comment]
Hi again, thank you for the quick answer:

> Hi @guillermo-carrasco
> 
> For debugging, as a first step you can check if all services are up and running. You can do so from the Admin UI (accessible from your account menu on the top right) and then click on `Services`.
> 

I can't see any services tab in the Admin UI, here is a capture of what I see:

![no-services](https://user-images.githubusercontent.com/1574147/68028037-22393c80-fcb4-11e9-924a-bd8071d4b24f.png)


> From cli, as root you can run the `/srv/hops/kagent/kagent/bin/status-all-local-services.sh`. Also useful are the application server logs under `/srv/hops/domains/domain1/logs/server.log`.
> 

With the CLI command, I see that some services are down:

![stopped_services](https://user-images.githubusercontent.com/1574147/68031208-798edb00-fcbb-11e9-9b1c-0cd66a7599bf.png)

And the logs contain lots of error messages, most of them `Connection refused`, do I need to enable some networking feature in the VM in GCE?

> You don't need to assign users to project when it is created, if no users are provided then the project's single member will be the user that created that project. For email to be sent, you need to set up your mail server config in the application server web console (default port 4848).
> 
> The GCP image is still the older version 0.10 which is also available as an virtualbox appliance if that could be more convenient for your setup https://hopsworks.readthedocs.io/en/0.10/getting_started/setups/single_machine.html#importing-an-ova-image (not available for 1.0 yet) On AWS there is a Hopsworks 1.0 AMI and you can easily install Hopsworks on a VM locally if you have a machine with at least 16GB of main memory https://hopsworks.readthedocs.io/en/1.0/getting_started/setups/single_machine.html
> 
> We are looking into ways to make it easier to deploy Hopsworks such as Docker, but it will not be available for the next release at least (scheduled for early December). The easiest way to get try out Hopsworks with GPUs as well is by registering for an account on https://www.hops.site which runs Hopsworks 1.0.

Thanks, we have our data infrastructure on GCP, so would like to avoid AWS if possible, I may try the single machine install on a fresh VM if I can't manage to fix the image you provide, and also to have the newest version.

I got an account to  https://www.hops.site, which is great! I have a question:

How can I access feature store from external python clients? say, a notebook running locally. How do I specify the credentials for the client? I have created an API key with scope feature store in my settings page, but I don't know how or where to attach it.

Thanks again!

**Comment by steffengr** [comment]
We don't have support for this on our master branch but you can try out a patch that I have created. You can install our cloud SDK locally and use it in local mode.

First put your API token into a local file called token.

Then you can install the library with pip and connect to the feature store:
`pip install git+https://github.com/steffengr/hopsworks-cloud-sdk@local`

Finally you can connect like this:
`from hops import featurestore as fs`
`fs.connect('hops.site', 'your_project_on_hops_site', secrets_store='local', api_token_file='yourpath/token')`

Note the the functionality of the cloud SDK is a bit limited in comparison to the normal one as the normal one is based on Spark and the SDK is built to work with Pandas instead. Some example usage can be found here:
https://github.com/logicalclocks/hops-examples/blob/master/notebooks/featurestore/aws/SageMakerFeaturestoreTourPython.ipynb

**Comment by tkakantousis** [comment]
@guillermo-carrasco You are right, the Services tab is only in Hopsworks 1.0. You can view the services in Monitoring and Control.

For now, it's better to do as root `/srv/hops/kagent/kagent/bin/shutdown-all-local-services.sh` and then `/srv/hops/kagent/kagent/bin/start-all-local-services.sh`

**Comment by tkakantousis** [comment]
Hi @guillermo-carrasco 
Is there any progress on the issue or shall we close it?

**Comment by guillermo-carrasco** [comment]
Sorry @tkakantousis I was away on absence and didn't have time to follow up on this. I will close the issue since I don't think I will continue exploring further right now.

Thanks for the help though, I will re-open the issue if I give it a second try eventually :smiley:
