### ISSUE TITLE
localhost is not accessible 

### ISSUE THREAD

**Issue by maneeshdisodia** [logicalclocks/hopsworks#451]
Hi,
I have completed the installation for a single machine i.e my laptop running ubuntu 18.04 LTS. steps I have followed: https://hopsworks.readthedocs.io/en/0.9/getting_started/setups/single_machine.html
installation takes around 1hr and i am able to see it on VirtualBox. 

On  accessing the "tail -f karamel-chef/nohup"  it say's

cat  karamel-chef/nohup.out
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/bionic64' version '20191218.0.0' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Using hostname "hopsworks0.logicalclocks.com" as node name for Chef...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 29206 (host) (adapter 1)
    default: 3306 (guest) => 20048 (host) (adapter 1)
    default: 9090 (guest) => 27889 (host) (adapter 1)
    default: 8080 (guest) => 20766 (host) (adapter 1)
    default: 8181 (guest) => 39758 (host) (adapter 1)
    default: 9009 (guest) => 25500 (host) (adapter 1)
    default: 4848 (guest) => 20001 (host) (adapter 1)
    default: 5601 (guest) => 33923 (host) (adapter 1)
    default: 3000 (guest) => 61755 (host) (adapter 1)
    default: 8083 (guest) => 51157 (host) (adapter 1)
    default: 8084 (guest) => 35895 (host) (adapter 1)
    default: 8086 (guest) => 55799 (host) (adapter 1)
    default: 2003 (guest) => 64851 (host) (adapter 1)
    default: 8888 (guest) => 28717 (host) (adapter 1)
    default: 11112 (guest) => 64246 (host) (adapter 1)
    default: 12358 (guest) => 29026 (host) (adapter 1)
    default: 8787 (guest) => 53652 (host) (adapter 1)
    default: 42011 (guest) => 42011 (host) (adapter 1)
    default: 42012 (guest) => 42012 (host) (adapter 1)
    default: 42013 (guest) => 42013 (host) (adapter 1)
    default: 2181 (guest) => 47596 (host) (adapter 1)
    default: 9092 (guest) => 54353 (host) (adapter 1)
    default: 16000 (guest) => 52593 (host) (adapter 1)
    default: 8000 (guest) => 25931 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:29206
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection reset. Retrying...
==> default: **Machine booted and ready!**
==> default: Checking for guest additions in VM...
==> default: Setting hostname...
==> default: Mounting shared folders...
    default: /vagrant => /home/machine/Downloads/karamel-chef
    default: /tmp/vagrant-chef/03ca3913f1400189ae6be0273a9b8488/cookbooks => /home/machine/Downloads/karamel-chef/cookbooks
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.

I am **unable to connect the GUI on the browser**, in other words, What URL I need to open. Please help me.

**Comment by tkakantousis** [comment]
It should be localhost:39758 as this is the forwarded 8181 port. 
By the way you are using an older unsupported version, latest is 1.1 https://hopsworks.readthedocs.io/en/1.1/getting_started/setups/single_machine.html

**Comment by maneeshdisodia** [comment]
Thanks for helping,
by doing all the new installation I am able to log in at the browser. Installation takes 6 hours. but again by clicking any button, it says this error. 
"**Could not create dummy Inode
Couldn't get the dummy Inode at: /tmp/demo_spark_admin000**"

**Comment by tkakantousis** [comment]
That means hopsfs is facing issues, that might happen if the host does not have enough resources for all the Hopsworks services. Minimum is 16GB of memory and 6 cores.

Support on Hopsworks has moved to https://community.hopsworks.ai/
